### ISSUE TITLE
Froyo as example app on Dear PyGui showcase

### ISSUE THREAD

**Issue by bandit-masked** [fIux-dev/froyo#1]
Hi,

Froyo looks like a good example app to add to the Dear PyGui Showcase (https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase).

Is that OK by you?

Thank you!

**Comment by fIux-dev** [comment]
Hello! Sure, that's OK with me!

Definitely honored to be considered - the app is pretty simple, but if it works as a good example, then I'm more than happy to approve. :)

**Comment by RaccoonMusicPlayer** [comment]
Thank you! The app has been added to the [showcase](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase). It was already useful for another user of Dear PyGui to learn about structuring his GUI code. 

Please keep us posted on future developments or new apps you may make with Dear PyGui!

If you are using the Discord server, which is the most active part of the community, please post your app examples there. If you do not use Discord, you could just post an issue with a link on [Dear PyGui's GitHub](https://github.com/hoffstadt/DearPyGui).

**Comment by bandit-masked** [comment]
I posted your app on Reddit in three communities. It's been doing quite well!

https://www.reddit.com/r/Python/comments/ts1iat/froyo_a_python_gui_utility_for_downloading_works/

https://www.reddit.com/r/DearPyGui/comments/ts13bt/froyo_a_python_gui_utility_for_downloading_works/

https://www.reddit.com/r/madeinpython/comments/ts1542/froyo_a_python_gui_utility_for_downloading_works/

I believe that at least 5 people starred your project on GitHub today.
